 export const recentCar = [
  {mark: 'Koenigsegg', type: 'Sport', img: '', gasoline: '90L', sreering: 'Manual', capacity: '2', currentPrice: "$99.00", oldPrice: "", description: "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.", stars: 4},
  {mark: 'Nissan GT - R', type: 'Sedan', img: '', gasoline: '80L', sreering: 'Manual', capacity: '2', currentPrice: "$80.00", oldPrice: "$100.00", description: "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.", stars: 4},
  {mark: 'Rolls-Royce', type: 'Couple', img: '', gasoline: '70L', sreering: 'Manual', capacity: '4', currentPrice: "$96.00", oldPrice: "", description: "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.", stars: 5},
  {mark: 'Koenigsegg', type: 'MPV', img: '', gasoline: '90L', sreering: 'Manual', capacity: '2', currentPrice: "$99.00", oldPrice: "", description: "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.", stars: 5},
  {mark: 'Nissan GT - R', type: 'Sport', img: '', gasoline: '80L', sreering: 'Manual', capacity: '2', currentPrice: "$80.00", oldPrice: "$100.00", description: "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.", stars: 3},
  {mark: 'Rolls-Royce', type: 'Sport', img: '', gasoline: '70L', sreering: 'Manual', capacity: '4', currentPrice: "$96.00", oldPrice: "$120.00", description: "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.", stars: 3},
]

export const recomendationCar = [
  {mark: 'All New Rush', type: 'Hatchback', img: '', gasoline: '70L', sreering: 'Manual', capacity: '6', currentPrice: "$72.00", oldPrice: "$80.00", description: "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.", stars: 4},
  {mark: 'CR - V', type: 'SUV', img: '', gasoline: '80L', sreering: 'Manual', capacity: '6', currentPrice: "$80.00", oldPrice: "$90.00", description: "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.", stars: 2},
  {mark: 'All New Terios', type: 'Hatchback', img: '', gasoline: '90L', sreering: 'Manual', capacity: '8', currentPrice: "$74.00", oldPrice: "", description: "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.", stars: 3},
  {mark: 'All New Rush', type: 'MPV', img: '', gasoline: '70L', sreering: 'Manual', capacity: '8', currentPrice: "$72.00", oldPrice: "$80.00", description: "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.", stars: 4},
  {mark: 'CR - V', type: 'SUV', img: '', gasoline: '80L', sreering: 'Manual', capacity: '8', currentPrice: "$80.00", oldPrice: "", description: "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.", stars: 5},
  {mark: 'All New Terios', type: 'SUV', img: '', gasoline: '90L', sreering: 'Manual', capacity: '6', currentPrice: "$74.00", oldPrice: "", description: "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.", stars: 2},
]